description: Sets up the repo for a typical CI job

name: Setup

inputs:
    node-version:
        description: "Node.js version to use"
        default: "lts/*"
        required: false

runs:
    steps:
        - name: ⎔ Setup node
          uses: actions/setup-node@v6
          with:
              node-version: ${{ inputs.node-version }}
        - name: 📥 Install dependencies
          run: npm install
          shell: bash
    using: composite
