import { findVariable } from "./find-variable"
import { getFunctionHeadLocation } from "./get-function-head-location"
import { getFunctionNameWithKind } from "./get-function-name-with-kind"
import { getInnermostScope } from "./get-innermost-scope"
import { getPropertyName } from "./get-property-name"
import type {
    StaticValue,
    StaticValueOptional,
    StaticValueProvided,
} from "./get-static-value"
import { getStaticValue } from "./get-static-value"
import { getStringIfConstant } from "./get-string-if-constant"
import type { HasSideEffectOptions } from "./has-side-effect"
import { hasSideEffect } from "./has-side-effect"
import { isParenthesized } from "./is-parenthesized"
import type { PatternMatherOptions } from "./pattern-matcher"
import { PatternMatcher } from "./pattern-matcher"
import type { ReferenceTrackerOptions } from "./reference-tracker"
import {
    CALL,
    CONSTRUCT,
    ESM,
    READ,
    ReferenceTracker,
} from "./reference-tracker"
import type {
    ArrowToken,
    ClosingBraceToken,
    ClosingBracketToken,
    ClosingParenToken,
    ColonToken,
    CommaToken,
    OpeningBraceToken,
    OpeningBracketToken,
    OpeningParenToken,
    PunctuatorToken,
    SemicolonToken,
} from "./token-predicate"
import {
    isArrowToken,
    isClosingBraceToken,
    isClosingBracketToken,
    isClosingParenToken,
    isColonToken,
    isCommaToken,
    isCommentToken,
    isNotArrowToken,
    isNotClosingBraceToken,
    isNotClosingBracketToken,
    isNotClosingParenToken,
    isNotColonToken,
    isNotCommaToken,
    isNotCommentToken,
    isNotOpeningBraceToken,
    isNotOpeningBracketToken,
    isNotOpeningParenToken,
    isNotSemicolonToken,
    isOpeningBraceToken,
    isOpeningBracketToken,
    isOpeningParenToken,
    isSemicolonToken,
} from "./token-predicate"

export default {
    CALL,
    CONSTRUCT,
    ESM,
    findVariable,
    getFunctionHeadLocation,
    getFunctionNameWithKind,
    getInnermostScope,
    getPropertyName,
    getStaticValue,
    getStringIfConstant,
    hasSideEffect,
    isArrowToken,
    isClosingBraceToken,
    isClosingBracketToken,
    isClosingParenToken,
    isColonToken,
    isCommaToken,
    isCommentToken,
    isNotArrowToken,
    isNotClosingBraceToken,
    isNotClosingBracketToken,
    isNotClosingParenToken,
    isNotColonToken,
    isNotCommaToken,
    isNotCommentToken,
    isNotOpeningBraceToken,
    isNotOpeningBracketToken,
    isNotOpeningParenToken,
    isNotSemicolonToken,
    isOpeningBraceToken,
    isOpeningBracketToken,
    isOpeningParenToken,
    isParenthesized,
    isSemicolonToken,
    PatternMatcher,
    READ,
    ReferenceTracker,
}
export type {
    StaticValue,
    StaticValueOptional,
    StaticValueProvided,
    HasSideEffectOptions,
    ReferenceTrackerOptions,
    PunctuatorToken,
    ArrowToken,
    CommaToken,
    SemicolonToken,
    ColonToken,
    OpeningParenToken,
    ClosingParenToken,
    OpeningBracketToken,
    ClosingBracketToken,
    OpeningBraceToken,
    ClosingBraceToken,
    PatternMatherOptions,
}
export {
    CALL,
    CONSTRUCT,
    ESM,
    findVariable,
    getFunctionHeadLocation,
    getFunctionNameWithKind,
    getInnermostScope,
    getPropertyName,
    getStaticValue,
    getStringIfConstant,
    hasSideEffect,
    isArrowToken,
    isClosingBraceToken,
    isClosingBracketToken,
    isClosingParenToken,
    isColonToken,
    isCommaToken,
    isCommentToken,
    isNotArrowToken,
    isNotClosingBraceToken,
    isNotClosingBracketToken,
    isNotClosingParenToken,
    isNotColonToken,
    isNotCommaToken,
    isNotCommentToken,
    isNotOpeningBraceToken,
    isNotOpeningBracketToken,
    isNotOpeningParenToken,
    isNotSemicolonToken,
    isOpeningBraceToken,
    isOpeningBracketToken,
    isOpeningParenToken,
    isParenthesized,
    isSemicolonToken,
    PatternMatcher,
    READ,
    ReferenceTracker,
}
